### ISSUE TITLE
 copy button für schema.org output

### ISSUE THREAD

**Issue by matthiaslexer** [if-loop/jason#1]
A copy button for the schema.org output would be cool.

**Comment by matthiaslexer** [comment]
https://sachinchoolur.github.io/ngclipboard/ will be added for copy support

**Comment by eliaskaerle** [comment]
Perfect!


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=ta&cv=9.8.157&pv=7.1.1&source=email_footer_2] On Fri, Feb 02, 2018 at 1:51pm, Matthias Lexer < notifications@github.com [notifications@github.com] > wrote:
https://sachinchoolur.github.io/ngclipboard/ [https://sachinchoolur.github.io/ngclipboard/] will be added for copy support

**Comment by eliaskaerle** [comment]
hi, any progress on that?

**Comment by matthiaslexer** [comment]
there is now a copy to clipboard button next to the json viewer
![image](https://user-images.githubusercontent.com/755094/36180778-230135e8-1122-11e8-9315-91fdaa0d392b.png)

**Comment by eliaskaerle** [comment]
Great, thanks!

On 14.02.2018 00:58, Matthias Lexer wrote:
> there is now a copy to clipboard button next to the json viewer
> ![image](https://user-images.githubusercontent.com/755094/36180778-230135e8-1122-11e8-9315-91fdaa0d392b.png)
> 
> 

-- 
Elias Kärle
web: http://elias.kaerle.com
skype: elias.kaerle
twitter: @eliaska
