### ISSUE TITLE
Umlaut issue!

### ISSUE THREAD

**Issue by eliaskaerle** [if-loop/jason#4]
In the JSON-LD file all Umlauts are wrong. Some encoding problem...

**Comment by matthiaslexer** [comment]
just checked the demofile, couldn't find any mistake. Have you got an example? @eliaskaerle

**Comment by eliaskaerle** [comment]
https://smtfy.it/rkJi6UxoeLG

maybe it happened because I uploaded manually. Maybe fixed after
semantify.it upload works...

On 02.02.2018 13:59, Matthias Lexer wrote:
> just checked the demofile, couldn't find any mistake. Have you got an example?
> 

-- 
Elias Kärle
web: http://elias.kaerle.com
skype: elias.kaerle
twitter: @eliaska

**Comment by matthiaslexer** [comment]
umlaute works 😆
