### ISSUE TITLE
upload to semantify.it doesn't work

### ISSUE THREAD

**Issue by eliaskaerle** [if-loop/jason#5]
File is written, but they all are empty!

**Comment by matthiaslexer** [comment]
it now works, uploads the full list as an array. is that okay?

**Comment by eliaskaerle** [comment]
Perfect!

On 14.02.2018 01:06, Matthias Lexer wrote:
> it now works, uploads the full list as an array. is that okay?
> 

-- 
Elias Kärle
web: http://elias.kaerle.com
skype: elias.kaerle
twitter: @eliaska
