### ISSUE TITLE
pure JSON in the "File (as JSON)"

### ISSUE THREAD

**Issue by eliaskaerle** [if-loop/jason#6]
In the "File (as JSON)"  section, pls show pure JSON (not the grouped view) for copy-pasting.

**Comment by matthiaslexer** [comment]
#1 will make this unnecessary

**Comment by eliaskaerle** [comment]
agree!


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=ta&cv=9.8.157&pv=7.1.1&source=email_footer_2] On Fri, Feb 02, 2018 at 1:52pm, Matthias Lexer < notifications@github.com [notifications@github.com] > wrote:
#1 [https://github.com/if-loop/jason/issues/1] will make this unnecessary

**Comment by matthiaslexer** [comment]
duplicates #1
